dataset_path: /scr2/muj_random_3_objects_new_02_control_range_fit_focused_20201006/
  #/scr2/muj_random_3_objects_new_20201003/
#/scr2/muj_random_3_objects_20201001/
  #/scr2/muj_random_10_objects_20200931/
  #[ /scr2/muj_random_10_objects_20200928/, /scr2/muj_random_10_objects_20200930/ ]
# /scr2/muj_random_20200728/
  #/scr2/muj_motion_primitive_20200722/

dataloading_params:
  num_workers: 6
  batch_size: 128
  idx_dict_path: /scr-ssd/sens_search_logging/runs/20201007_training_2_w_3smallobjects_fit_w_entropy/val_train_split.pkl
    #/scr-ssd/sens_search_logging/models/20201004_training_1_w_10objects_regression/val_train_split.pkl
    #/scr-ssd/sens_search_logging/runs/20201001_training_0_w_10objects_regression/val_train_split.pkl
  num_objects: 3
    #/scr-ssd/sens_search_logging/models/20200802_training_2_rl_policy/val_train_split.pkl
    #/scr-ssd/sens_search_logging/models/20200801_training_2_rl_policy/val_train_split.pkl

training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 5000
  val_ratio: 0.1
  dev_num: 20 # number of datapoints in the development set
  use_GPU: True
  run_mode: 1 # 0 - development, 1 - training, 2 - testing

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_notes: "_w_3smallobjects_fit_voting"

dataset_keys: ["force_hi_freq", "action", "proprio", "rel_proprio", "contact", "peg_vector", "hole_vector", "fit_vector", "hole_sites", 'done'] #, 'image', 'depth']

info_flow:
  # History_Encoder:
  #   train: 1
  #   model_folder: ''
  #   epoch: 0
  #   init_args:
  #     num_objects: 4
  #     action_size: 3
  #     proprio_size: 12
  #     force_size: [6, 50]
  #     dropout_prob: 0.5
  #     min_length: 20
  #   inputs:
  #     rel_proprio: dataset
  #     action: dataset
  #     force_hi_freq: dataset
  #     contact: dataset
  #     tool_idx: dataset
  #     state_idx: dataset
  #     include_label: dataset
  #     padding_mask: dataset
  #     epoch: dataset
  #   outputs:
  #     pos_est:
  #       inputs:
  #         final_rel_pos: dataset
  #       # losses:
  #       #   L2:
  #       #     weight: 5
  #       #     logging_name: Position_Estimate
  #       evals:
  #         Continuous_Error:
  #           logging_name:  Pos_Err_Force
  #     pos_est_params:
  #       inputs:
  #         final_rel_pos: dataset
  #       losses:
  #         Gaussian_NLL:
  #           weight: 0.1
  #           logging_name: Position_Estimate
  #     obs_logits:
  #       inputs:
  #         fit_idx: dataset
  #       losses: 
  #         Multinomial_NLL:
  #           logging_name: Obs_Shape_Class
  #     obs_inputs:
  #       inputs:
  #         fit_idx: dataset
  #       evals:
  #         Multinomial_Accuracy:
  #           logging_name: obs_classifier_accuracy
  StatePosSensor_wConstantUncertainty:
    train: 1
    model_folder: ''
    epoch: 0 #5000
    init_args:
      num_objects: 3
      action_size: 3
      proprio_size: 12
      force_size: [6, 50]
      dropout_prob: 0.5
      min_length: 20
    inputs:
      rel_proprio: dataset
      rel_pos_prior_mean: dataset
      rel_pos_prior_var: dataset
      state_prior: dataset
      action: dataset
      force_hi_freq: dataset
      contact: dataset
      tool_idx: dataset
      fit_idx: dataset
      new_tool_idx: dataset
      new_fit_idx: dataset
      state_idx: dataset
      padding_mask: dataset
      input_length: dataset
      epoch: dataset
    outputs:
      # pos_est:
      #   inputs:
      #     final_rel_pos: dataset
      #   # losses:
      #   #   L2:
      #   #     weight: 5
      #   #     logging_name: Position_Estimate
      #   evals:
      #     Continuous_Error:
      #       logging_name:  Pos_Err_Posterior
      # pos_est_params:
      #   inputs:
      #     final_rel_pos: dataset
      #   losses:
      #     Gaussian_NLL:
      #       weight: 0.1
      #       logging_name: Position_Estimate
      vote_logits:
        inputs: 
          vote_idx: StatePosSensor_wConstantUncertainty
        losses:
          Multinomial_NLL:
            logging_name: Voting_Classifier
      vote_inputs:
        inputs: 
          vote_idx: StatePosSensor_wConstantUncertainty
        evals:
          Multinomial_Accuracy:
            logging_name: Vote_Classifier_Accuracy
      # obs_logits:
      #   inputs:
      #     fit_idx: dataset
      #   losses: 
      #     Multinomial_NLL:
      #       logging_name: Obs_Shape_Class
      # obs_inputs:
      #   inputs:
      #     fit_idx: dataset
      #   evals:
      #     Multinomial_Accuracy:
      #       logging_name: obs_classifier_accuracy
      # obs_logprobs_inputs:
      #   losses:
      #     Neg_Multinomial_Entropy:
      #      # weight: 0.25
      #       logging_name: ent_max_mult
      # state_logits:
      #   inputs:
      #     state_idx: dataset
      #   losses: 
      #     Multinomial_NLL:
      #       logging_name: State_Shape_Class
      # state_inputs:
      #   inputs:
      #     state_idx: dataset
      #   evals:
      #     Multinomial_Accuracy:
      #       logging_name: state_classifier_accuracy
 