dataset_path: /scr2/muj_random_20200728/
  #/scr2/muj_motion_primitive_20200722/

dataloading_params:
  num_workers: 6
  batch_size: 128
  idx_dict_path: /scr-ssd/sens_search_logging/models/20200802_training_2_rl_policy/val_train_split.pkl
    #/scr-ssd/sens_search_logging/models/20200801_training_2_rl_policy/val_train_split.pkl

training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 5000
  val_ratio: 0.1
  dev_num: 20 # number of datapoints in the development set
  use_GPU: True
  run_mode: 1 # 0 - development, 1 - training, 2 - testing

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_notes: "_rl_policy"

dataset_keys: ["force_hi_freq", "action", "rel_proprio", "contact", "peg_vector", "hole_vector", "fit_vector", "hole_sites", 'done'] #, 'image', 'depth']

info_flow:
  # History_Encoder_wUncertainty:
  #   train: 1
  #   model_folder: '' 
  #   epoch: 0 #5000
  #   init_args:
  #     num_tools: 3
  #     num_states: 3
  #     num_options: 2
  #     action_size: 3
  #     proprio_size: 12
  #     force_size: [6, 50]
  #     dropout_prob: 0.5
  #     min_length: 20
  #   inputs:
  #     rel_proprio: dataset
  #     rel_pos_shift: dataset
  #     rel_pos_shift_var: dataset
  #     state_prior: dataset
  #     action: dataset
  #     force_hi_freq: dataset
  #     contact: dataset
  #     tool_idx: dataset
  #     padding_mask: dataset
  #     epoch: dataset
  #   outputs:
  #     pos_est:
  #       inputs:
  #         rel_pos_final: dataset
  #       losses:
  #         L1:
  #           weight: 500
  #           logging_name: Position_Estimate
  #       evals:
  #         Continuous_Error:
  #           logging_name:  Pos_Err_Force
  #     obs_logits:
  #       inputs:
  #         state_idx: dataset
  #       losses: 
  #         Multinomial_NLL:
  #           logging_name: Obs_Shape_Class
  #     obs_inputs:
  #       inputs:
  #         state_idx: dataset
  #       evals:
  #         Multinomial_Accuracy:
  #           logging_name: obs_classifier_accuracy
  #     state_logits:
  #       inputs:
  #         state_idx: dataset
  #       losses: 
  #         Multinomial_Margin_Loss:
  #         # Multinomial_NLL:
  #           logging_name: State_Shape_Class
  #     state_inputs:
  #       inputs:
  #         state_idx: dataset
  #       evals:
  #         Multinomial_Accuracy:
  #           logging_name: state_classifier_accuracy
  History_Encoder_Baseline:
    train: 1
    model_folder: '' 
    epoch: 0 #5000
    init_args:
      num_tools: 3
      num_states: 3
      num_options: 2
      action_size: 3
      proprio_size: 12
      force_size: [6, 50]
      dropout_prob: 0.5
      min_length: 20
    inputs:
      rel_proprio: dataset
      action: dataset
      force_hi_freq: dataset
      contact: dataset
      tool_idx: dataset
      padding_mask: dataset
      epoch: dataset
    outputs:
      pos_est:
        inputs:
          rel_pos_final: dataset
        losses:
          L1:
            weight: 500
            logging_name: Position_Estimate
        evals:
          Continuous_Error:
            logging_name:  Pos_Err_Force
      obs_logits:
        inputs:
          state_idx: dataset
        losses: 
          Multinomial_NLL:
            logging_name: Obs_Shape_Class
      obs_inputs:
        inputs:
          state_idx: dataset
        evals:
          Multinomial_Accuracy:
            logging_name: obs_classifier_accuracy