model_params:
  z_dim: 128

dataloading_params:
  dataset_path: "/juno/group/muj_multimod_dataset1/"
  num_workers: 6
  batch_size: 128
  num_steps: 10
  idx_dict_path: ""

training_params:
  seed: 1234
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 25
  val_ratio: 0.05
  use_GPU: True
  curriculum: [2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10] #[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2] #

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_description: "debugging" #Options include: debugging, training, testing
  run_notes: "_inital_testing"

debugging_params:
  debugging_val: 1.0 ### 1.0 for True,  0.0 for False
  save_model_val: 0.0 ### 1.0 for True,  0.0 for False 

info_flow:
  dataset:
    outputs:
      image: [3, 128, 128]
      joint_pos: [7]
      joint_vel: [7]
      force: [6]
      action: [3]
      proprio: [12]
      contact: [1]
  EEFRC_Dynamics:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      proprio: "dataset"
      force: "dataset"
      action: "dataset"
      joint_pos: "dataset"
      joint_vel: "dataset"
      contact: "dataset"
      epoch: "dataset"
    outputs:
      contact:
        loss: "BCE_pred_multistep"
        loss_name: "contact_pred_multistep"
        weight: 1
        inputs:
          contact: "dataset"
      force_pred:
        loss: "Pred_multistep"
        loss_name: "force_pred_multistep"
        weight: 1
        inputs:
          force: "dataset"
      prop_pred:
        loss: "Pred_multistep"
        loss_name: "proprio_pred_multistep"
        weight: 1
        inputs:
          proprio: "dataset"
      joint_pos_pred:
        loss: "Pred_multistep"
        loss_name: "joint_pos_pred_multistep"
        weight: 1
        inputs:
          joint_pos: "dataset"
      joint_vel_pred:
        loss: "Pred_multistep"
        loss_name: "joint_vel_pred_multistep"
        weight: 1
        inputs:
          joint_vel: "dataset"
  # Simple_Multimodal_Hist1:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     action: "dataset"
  #     contact: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # z_dist:
  #     #   loss: "Prior_multistep"
  #     #   loss_name: "relative_random"
  #     #   weight: 0.01
  #     z_pred:
  #       loss: "Hist1_pred_multistep"
  #       loss_name: "dynamics_loss"
  #       weight: 100.0
  #       inputs:
  #         z: "Simple_Multimodal_Hist1"
  #     image_dec:
  #       loss: "Rec_image_multistep"
  #       loss_name: "image_rec_multistep"
  #       weight: 0.0001
  #       inputs:
  #         image: "dataset"
  #     prop_dec:
  #       loss: "Rec_multistep"
  #       loss_name: "proprio_rec_multistep"
  #       weight: 10
  #       inputs:
  #         proprio: "dataset"
  # LSTM_Multimodal:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     action: "dataset"
  #     contact: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # z_dist:
  #     #   loss: "Prior_multistep"
  #     #   loss_name: "relative_random"
  #     #   weight: 0.01
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 500.0
  #       inputs:
  #         z: ""
  #     image_dec:
  #       loss: "Rec_image_multistep"
  #       loss_name: "image_rec_multistep"
  #       weight: 0.0001
  #       inputs:
  #         image: "dataset"
  #     prop_dec:
  #       loss: "Rec_multistep"
  #       loss_name: "proprio_rec_multistep"
  #       weight: 10
  #       inputs:
  #         proprio: "dataset"

  # Contact_Force_Multimodal:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     force: "dataset"
  #     action: "dataset"
  #     contact: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # z_dist:
  #     #   loss: "Prior_multistep"
  #     #   loss_name: "relative_random"
  #     #   weight: 0.01
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 1.0
  #       inputs:
  #         z: "Simple_Multimodal"
  #     image_dec:
  #       loss: "Rec_image_multistep"
  #       loss_name: "image_rec_multistep"
  #       weight: 0.0001
  #       inputs:
  #         image: "dataset"
  #     prop_dec:
  #       loss: "Rec_multistep"
  #       loss_name: "proprio_rec_multistep"
  #       weight: 10
  #       inputs:
  #         proprio: "dataset"
  #     frc_dec:
  #       loss: "Rec_multistep"
  #       loss_name: "force_rec_multistep"
  #       weight: 10
  #       inputs:
  #         force: "dataset"
  #     contact:
  #       loss: "BCE_multistep"
  #       loss_name: "contact_class_multistep"
  #       weight: 10
  # Contact_Multimodal:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     action: "dataset"
  #     contact: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # z_dist:
  #     #   loss: "Prior_multistep"
  #     #   loss_name: "relative_random"
  #     #   weight: 0.01
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 1.0
  #       inputs:
  #         z: "Simple_Multimodal"
  #     image_dec:
  #       loss: "Rec_image_multistep"
  #       loss_name: "image_rec_multistep"
  #       weight: 0.0001
  #       inputs:
  #         image: "dataset"
  #     prop_dec:
  #       loss: "Rec_multistep"
  #       loss_name: "proprio_rec_multistep"
  #       weight: 10
  #       inputs:
  #         proprio: "dataset"
  #     contact:
  #       loss: "BCE_multistep"
  #       loss_name: "contact_class_multistep"
  #       weight: 10
  # VAE_Multimodal:
  #   train: 0
  #   model_folder: "/scr-ssd/sens_search_logging/models/201912101814_debugging_70_inital_testing/"
  #   epoch_num: 20
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # params:
  #     #   loss: "KL_DIV_multistep"
  #     #   loss_name: "kl_div_multistep"
  #     #   weight: 0.0005
  #     # image_dec:
  #     #   loss: "Rec_image_multistep"
  #     #   loss_name: "image_rec_multistep"
  #     #   weight: 0.0001
  #     #   inputs:
  #     #     image: "dataset"
  #     # prop_dec:
  #     #   loss: "Rec_multistep"
  #     #   loss_name: "proprio_rec_multistep"
  #     #   weight: 1.0
  #     #   inputs:
  #     #     proprio: "dataset"
  # Selfsupervised_Multimodal:
  #   train: 0
  #   model_folder: "/scr-ssd/sens_search_logging/models/201912101814_debugging_70_inital_testing/"
  #   epoch_num: 20
  #   inputs:
  #     image: "dataset"
  #     proprio: "dataset"
  #     proprio_up: "dataset"
  #     contact: "dataset"
  #     action: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     z:
  #       loss: ""
  #     # params:
  #     #   loss:  "" #"KL_DIV_multistep"
  #     #   loss_name: "kl_div_multistep"
  #     #   weight: 0.0005
  #     # image_pred:
  #     #   loss:  "" #"Pred_image_multistep"
  #     #   loss_name: "image_pred_multistep"
  #     #   weight: 0.001
  #     #   inputs:
  #     #     image: "dataset"
  #     # eepos_pred:
  #     #   loss: "Pred_eepos_multistep"
  #     #   loss_name: "eepos_pred_multistep"
  #     #   weight: 0.0001
  #     #   inputs:
  #     #     proprio: "dataset"
  #     # contact_pred:
  #     #   loss: "BCE_multistep"
  #     #   loss_name: "contact_pred_multistep"
  #     #   weight: 1.0
  #     # pairing_class:
  #     #   loss: "BCE_multistep"
  #     #   loss_name: "pairing_class_multistep"
  #     #   weight: 1.0
  # Selfsupervised_Dynamics:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     action: "dataset"
  #     z: "Selfsupervised_Multimodal"
  #     epoch: "dataset"
  #   outputs:
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 1.0
  #       inputs:
  #         z: "Selfsupervised_Multimodal"
  # VAE_Dynamics:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     action: "dataset"
  #     z: "VAE_Multimodal"
  #     epoch: "dataset"
  #   outputs:
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 1.0
  #       inputs:
  #         z: "Relational_Multimodal"
  # Relational_Dynamics:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     action: "dataset"
  #     z: "Relational_Multimodal"
  #     epoch: "dataset"
  #   outputs:
  #     z_pred:
  #       loss: "Pred_multistep_list"
  #       loss_name: "dynamics_loss"
  #       weight: 1.0
  #       inputs:
  #         z: "Relational_Multimodal"



