model_params:
  z_dim: 128

dataloading_params:
  dataset_path: "/scr2/dataset_senssearch/"
  num_workers: 6
  batch_size: 128
  num_steps: 10
  idx_dict_path: "" #/scr-ssd/sens_search_logging/runs/201911191154_debugging_17_inital_testing/val_train_split.pkl"

training_params:
  seed: 1234
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 25
  val_ratio: 0.05
  use_GPU: True
  curriculum: [1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10]

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_description: "debugging" #Options include: debugging, training, testing
  run_notes: "_inital_testing"

debugging_params:
  debugging_val: 1.0 ### 1.0 for True,  0.0 for False
  save_model_val: 0.0 ### 1.0 for True,  0.0 for False 

info_flow:
  dataset:
    outputs:
      image: [3, 128, 128]
      force: [6]
      action: [6]
      proprio: [12]
  Simple_Multimodal:
    inputs:
      image: "dataset"
      force: "dataset"
      proprio: "dataset"
      action: "dataset"
      epoch: "dataset"
    outputs:
      params:
        loss: "KL_DIV_multistep"
        weight: 0.0005
        inputs:
          params: "Simple_Multimodal"
      image_pred:
        loss: "MSE_image_multistep"
        weight: 0.0001
        inputs:
          image_pred: "Simple_Multimodal"
          image: "dataset"
      proprio_pred:
        loss: "MSE_proprio_multistep"
        weight: 1.0
        inputs:
          proprio_pred: "Simple_Multimodal"
          proprio: "dataset"
      force_pred:
        loss: "MSE_force_multistep"
        weight: 1.0
        inputs:
          force_pred: "Simple_Multimodal"
          force: "dataset"
  Simple_Multimodal_woutforce:
    inputs:
      image: "dataset"
      proprio: "dataset"
      action: "dataset"
      epoch: "dataset"
    outputs:
      params:
        loss: "KL_DIV_multistep"
        weight: 0.0005
        inputs:
          params: "Simple_Multimodal_woutforce"
      image_pred:
        loss: "MSE_image_multistep"
        weight: 0.0001
        inputs:
          image_pred: "Simple_Multimodal_woutforce"
          image: "dataset"
      proprio_pred:
        loss: "MSE_proprio_multistep"
        weight: 1.0
        inputs:
          proprio_pred: "Simple_Multimodal_woutforce"
          proprio: "dataset"
  Simple_Multimodal_woutforcewfusion:
    inputs:
      image: "dataset"
      proprio: "dataset"
      action: "dataset"
      epoch: "dataset"
    outputs:
      params:
        loss: "KL_DIV_multistep"
        weight: 0.0005
        inputs:
          params: "Simple_Multimodal_woutforcewfusion"
      image_pred:
        loss: "MSE_image_multistep"
        weight: 0.0001
        inputs:
          image_pred: "Simple_Multimodal_woutforcewfusion"
          image: "dataset"
      proprio_pred:
        loss: "MSE_proprio_multistep"
        weight: 1.0
        inputs:
          proprio_pred: "Simple_Multimodal_woutforcewfusion"
          proprio: "dataset"
  EEpos_dynamics:
    inputs:
      proprio: "dataset"
      action: "dataset"
      epoch: "dataset"
    outputs:
      proprio_pred:
        loss: "MSE_proprio_multistep"
        weight: 1.0
        inputs:
          proprio_pred: "EEpos_dynamics"
          proprio: "dataset"



