model_params:
  z_dim: 128

dataloading_params:
  dataset_path: "/scr2/dataset_senssearch/"
  num_workers: 6
  batch_size: 128
  num_steps: 10
  idx_dict_path: ""

training_params:
  seed: 1234
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 25
  val_ratio: 0.05
  use_GPU: True
  curriculum: [3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10]

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_description: "debugging" #Options include: debugging, training, testing
  run_notes: "_inital_testing"

debugging_params:
  debugging_val: 1.0 ### 1.0 for True,  0.0 for False
  save_model_val: 0.0 ### 1.0 for True,  0.0 for False 

info_flow:
  dataset:
    outputs:
      image: [3, 128, 128]
      force: [6]
      action: [3]
      proprio: [12]
      contact: [1]
  Relational_Multimodal:
    inputs:
      image: "dataset"
      proprio: "dataset"
      epoch: "dataset"
    outputs:
      z_perm:
        loss: "Relational_multistep"
        loss_name: "relative_random"
        weight: 1.0
      image_dec:
        loss: "Rec_image_multistep"
        loss_name: "image_rec_multistep"
        weight: 0.001
        inputs:
          image: "dataset"
      prop_dec:
        loss: "Rec_multistep"
        loss_name: "proprio_rec_multistep"
        weight: 10
        inputs:
          proprio: "dataset"
  VAE_Multimodal:
    inputs:
      image: "dataset"
      proprio: "dataset"
      epoch: "dataset"
    outputs:
      params:
        loss: "KL_DIV_multistep"
        loss_name: "kl_div_multistep"
        weight: 0.0005
      image_dec:
        loss: "Rec_image_multistep"
        loss_name: "image_rec_multistep"
        weight: 0.0001
        inputs:
          image: "dataset"
      prop_dec:
        loss: "Rec_multistep"
        loss_name: "proprio_rec_multistep"
        weight: 1.0
        inputs:
          proprio: "dataset"
  Selfsupervised_Multimodal:
    inputs:
      image: "dataset"
      proprio: "dataset"
      proprio_up: "dataset"
      contact: "dataset"
      action: "dataset"
      epoch: "dataset"
    outputs:
      params:
        loss: "KL_DIV_multistep"
        loss_name: "kl_div_multistep"
        weight: 0.0005
      eepos_pred:
        loss: "Pred_eepos_multistep"
        loss_name: "eepos_pred_multistep"
        weight: 0.0001
        inputs:
          proprio: "dataset"
      contact_pred:
        loss: "BCE_multistep"
        loss_name: "contact_pred_multistep"
        weight: 1.0
      pairing_class:
        loss: "BCE_multistep"
        loss_name: "pairing_class_multistep"
        weight: 1.0




