model_params:
  z_dim: 64
  min_steps: 20
  num_options: 3

dataloading_params:
  dataset_path: "/scr2/muj_senssearch_dataset10HZ_slide_nonoise_2020417/"
  num_workers: 0
  batch_size: 64
  num_trajectories: 500
  idx_dict_path: "/scr-ssd/sens_search_logging/runs/202004180840_debugging_0_10HZ/val_train_split.pkl"


training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 2500
  val_ratio: 0.1
  use_GPU: True
  
logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_description: "debugging" #Options include: debugging, training, testing
  run_notes: "_10HZ"

debugging_params:
  debugging_val: 1.0 ### 1.0 for True,  0.0 for False
  save_model_val: 0.0 ### 1.0 for True,  0.0 for False 

info_flow:
  dataset:
    outputs:
      # rgbd: [4, 128, 128]
      joint_pos: [7]
      joint_vel: [7]
      force_hi_freq: [6, 250]
      action: [3]
      macro_action: [6]
      proprio: [12]
      contact: [1]
      peg_type: [3]
      hole_type: [3]
      insertion: [1]
  Options_Sensor:
    train: 0
    model_folder: "/scr-ssd/sens_search_logging/models/202004191028_debugging_12_10HZ/"
    epoch_num: 1810
    inputs:
      proprio_diff: "dataset"
      force_hi_freq: "dataset"
      action: "dataset"
      macro_action: "dataset"
      peg_type: "dataset"
      contact_diff: "dataset"
      proprio_diff_comp: "dataset"
      force_hi_freq_comp: "dataset"
      action_comp: "dataset"
      macro_action_comp: "dataset"
      peg_type_comp: "dataset"
      contact_diff_comp: "dataset"
      padding_mask: "dataset"
      epoch: "dataset"
    outputs:
      options_class:
        loss: "CE"
        loss_name: "Options_Class"
        weight: 1
        inputs:
          hole_type: "dataset"
      options_class_comp:
        loss: "CE"
        loss_name: "Options_Class_Comp"
        weight: 1
        inputs:
          hole_type_comp: "dataset"
  Insertion_Predictor:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      macro_action: "dataset"
      peg_type: "dataset"
      hole_type: "dataset"
      epoch: "dataset"
    outputs:
      insert_class:
        loss: "BCE"
        loss_name: "Insert_Pred"
        weight: 1
        inputs:
          insertion_bool: "dataset"
  Options_Predictor:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      macro_action: "dataset"
      peg_type: "dataset"
      hole_type: "dataset"
      macro_action_comp: "dataset"
      peg_type_comp: "dataset"
      hole_type_comp: "dataset"
      epoch: "dataset"
    outputs:
      options_class:
        loss: "Mult_KL"
        loss_name: "Options_Class"
        weight: 1
        inputs:
          options_class: "Options_Sensor"
      conf_class:
        loss: "CE"
        loss_name: "Confusion_Class"
        weight: 1
        inputs:
          hole_est: "Options_Sensor"
      options_comp_class:
        loss: "Mult_KL"
        loss_name: "Options_Class_Comp"
        weight: 1
        inputs:
          options_class_comp: "Options_Sensor"
      conf_comp_class:
        loss: "CE"
        loss_name: "Confusion_Class_Comp"
        weight: 1
        inputs:
          hole_est_comp: "Options_Sensor"
  Feeling_Distance:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      macro_action: "dataset"
      macro_action_comp: "dataset"
      peg_type: "dataset"
      peg_type_comp: "dataset"
      hole_type: "dataset"
      hole_type_comp: "dataset"
      epoch: "dataset"
    outputs:
      distances:
        loss: "MSE"
        loss_name: "Feeling_Distance_Pred"
        weight: 1
        inputs:
          distances: "Options_Sensor"
  # Options_Confusion:
  #   train: 0
  #   model_folder: "/scr-ssd/sens_search_logging/models/202004150827_debugging_5_10HZ/"
  #   epoch_num: 100
  #   inputs:
  #     init_pos: "dataset"
  #     command_pos: "dataset"
  #     peg_type: "dataset"
  #     hole_type: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     options_class:
  #       loss: "CE"
  #       loss_name: "Options_Confusion"
  #       weight: 1
  #       inputs:
  #         hole_est: "Options_Classifier"
  # Options_Confusion_Mat:
  #   train: 0
  #   model_folder: "/scr-ssd/sens_search_logging/models/202004150859_debugging_21_10HZ/"
  #   epoch_num: 1
  #   inputs:
  #     init_pos: "dataset"
  #     command_pos: "dataset"
  #     peg_type: "dataset"
  #     hole_type: "dataset"
  #     hole_est: "Options_Classifier"



