model_params:
  z_dim: 64
  min_steps: 20
  num_options: 3

dataloading_params:
  dataset_path: "/scr2/muj_senssearch_dataset10HZ_slide/"
  num_workers: 4
  batch_size: 64
  num_trajectories: 500
  idx_dict_path: ""
  # "/scr-ssd/sens_search_logging/runs/202002200925_debugging_15_10HZ_wensemble/val_train_split.pkl" # - dataset "/scr2/muj_senssearch_dataset10HZ_sliding/"
  #"/scr-ssd/sens_search_logging/runs/202002180859_debugging_5_2HZ_wrgbd/val_train_split.pkl" # - dataset "/scr2/muj_senssearch_dataset2HZ_winsert/"
    #"/scr-ssd/sens_search_logging/runs/202002111509_debugging_19_2HZ_wrgbd/val_train_split.pkl" # - dataset "/scr2/muj_senssearch_dataset_2HZ/"


training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 1250
  val_ratio: 0.05
  use_GPU: True
  curriculum: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] #[] #[10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20] #[2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10] #[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2] #
#  # [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,9,9,9,9,10,10,10,10,11,11,11,11,12,12,12,12,12] #
logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_description: "debugging" #Options include: debugging, training, testing
  run_notes: "_10HZ"

debugging_params:
  debugging_val: 1.0 ### 1.0 for True,  0.0 for False
  save_model_val: 0.0 ### 1.0 for True,  0.0 for False 

info_flow:
  dataset:
    outputs:
      # rgbd: [4, 128, 128]
      joint_pos: [7]
      joint_vel: [7]
      force_hi_freq: [6, 250]
      action: [3]
      proprio: [12]
      contact: [1]
      peg_type: [3]
      hole_type: [3]
      final_point: [3]
  Options_ClassifierTransformer:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      proprio_diff: "dataset"
      force_hi_freq: "dataset"
      action: "dataset"
      peg_type: "dataset"
      contact_diff: "dataset"
      padding_mask: "dataset"
      length: "dataset"
      epoch: "dataset"
    outputs:
      options_class:
        loss: "CE"
        loss_name: "Options_Class"
        weight: 1
        inputs:
          hole_type: "dataset"
      origin_params:
        loss: "Multivariate_Normal_Logprob"
        loss_name: "Position_Detection"
        weight: 1
        inputs:
          final_point: "dataset"
      # options_class_ss:
      #   loss: "CE"
      #   loss_name: "Options_Class1"
      #   weight: 1
      #   inputs:
      #     hole_type_ss: "dataset"
      # contrastive:
      #   loss: "Contrastive"
      #   loss_name: "Contrastive_Loss"
      #   weight: 10
  # Dynamics:
  #   train: 1
  #   model_folder: "/scr-ssd/sens_search_logging/models/202002101946_debugging_14_2HZ_wrgbd/"
  #   epoch_num: 24
  #   inputs:
  #     rgbd: "dataset"
  #     proprio: "dataset"
  #     force_hi_freq: "dataset"
  #     action: "dataset"
  #     joint_pos: "dataset"
  #     joint_vel: "dataset"
  #     peg_type: "dataset"
  #     hole_type: "dataset"
  #     contact: "dataset"
  #     epoch: "dataset"
  #   outputs:
  #     pos_diff_dir:
  #       loss: "Angle_multistep"
  #       loss_name: "pos_diff_dir_est"
  #       weight: 1.0
  #       offset: 0
  #       inputs:
  #         pos_diff_d: "dataset"
  #     pos_diff_mag:
  #       loss: "Mag_multistep"
  #       loss_name: "pos_diff_mag_est"
  #       weight: 10000
  #       offset: 0
  #       inputs:
  #         pos_diff_m: "dataset"