relative_path: "../../supervised_learning/"
dataset_path: "/scr2/muj_senssearch_dataset10HZ_SAC_20200629/" 
#"/scr2/muj_senssearch_dataset10HZ_SAC_20200625/" #"/scr2/muj_senssearch_dataset10HZ_slide_20200517/" 
  #
 # "/scr2/muj_senssearch_dataset10HZ_slide_20200517_cross/"
# "/scr2/muj_senssearch_dataset10HZ_slide_20200517_rect/" 
dataloading_params:
  num_workers: 4
  batch_size: 128
  idx_dict_path: "/scr-ssd/sens_search_logging/runs/20200630_training_23_rl_policy/val_train_split.pkl"
  #"/scr-ssd/sens_search_logging/runs/20200627_training_25_rl_policy/val_train_split.pkl" # SAC 0625
  #"/scr-ssd/sens_search_logging/runs/20200530_training_12_fit_wexpanded_action/val_train_split.pkl" 
  #"/scr-ssd/sens_search_logging/runs/20200530_training_12_fit_wexpanded_action/val_train_split.pkl" # full
  # "/scr-ssd/sens_search_logging/runs/20200531_training_21_fit_wexpanded_action/val_train_split.pkl" # cross
#"/scr-ssd/sens_search_logging/runs/20200530_training_8_fit_wexpanded_action/val_train_split.pkl" # rect
training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 5000
  val_ratio: 0.1
  dev_num: 20 # number of datapoints in the development set
  use_GPU: True
  run_mode: 1 # 0 - development, 1 - training, 2 - testing

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_notes: "_rl_policy"

custom_params:
  image_size: [4, 128, 128]
  force_size: [6, 50]
  action_size: 3
  macro_action_size: 4
  proprio_size: 12
  min_length: 20
  num_trajectories: 500
  dropout_prob: 0.2
  
dataset_keys: ["force_hi_freq", "action", "rel_proprio", "contact", "peg_vector", "hole_vector", "fit_vector", "rgbd", "hole_sites"]
  # rgbd:
  # joint_pos:
  # joint_vel:
  # insertion:

info_flow:
  Options_Sensor:
    train: 0
    model_folder: "/scr-ssd/sens_search_logging/models/20200630_training_45_rl_policy/" #"/scr-ssd/sens_search_logging/models/20200627_training_25_rl_policy/" #"/scr-ssd/sens_search_logging/models/20200602_training_7_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200601_training_44_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200601_training_7_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200531_training_27_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200531_training_21_fit_wexpanded_action/"  #"/scr-ssd/sens_search_logging/models/20200530_training_12_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200529_training_45_fit_wexpanded_action/" #"/scr-ssd/sens_search_logging/models/20200529_training_20_fit_wexpanded_action/"
    epoch_num: 2300
    inputs:
      rel_proprio_diff: "dataset"
      force_hi_freq: "dataset"
      action: "dataset"
      rgbd_first: dataset
      rgbd_last: dataset
      contact_diff: "dataset"
      padding_mask: "dataset"
      pol_idx: "dataset"
      tool_idx: "dataset"
      state_idx: "dataset"
      cand_idx: "dataset"
      epoch: "dataset"
    outputs:
      options_class:
        inputs:
          fit_label: dataset
        losses: 
          Multinomial_NLL_Ensemble:
            logging_name: Options_Class
      pos_est:
        inputs:
          hole_sites: dataset
        losses:
          L1_Ensemble:
            weight: 5
            logging_name: Cand_Pos_Est
        evals:
          Continuous_Error_Ensemble:
            logging_name: Position Error Metrics
      options_inputs:
        inputs:
          fit_label: dataset
        evals:
          Multinomial_Accuracy_Ensemble:
            logging_name: "classifier_accuracy"
          # Multinomial_Entropy_Ensemble:
          #   logging_name: "classifier_entropy"
          # Multinomial_Entropy_Spread_Ensemble:
          #   logging_name: "classifier_entropy_gap"
  Options_ConfNet:
    train: 1
    model_folder: "" #"/scr-ssd/sens_search_logging/models/20200627_training_33_rl_policy/" #"/scr-ssd/sens_search_logging/models/20200607_training_3_fit_wexpanded_action/"
    epoch_num: 0
    inputs:
      macro_action: "dataset"
      policy_embed: "Options_Sensor"
      tool_embed: "Options_Sensor"
      state_embed: "Options_Sensor"
      epoch: "dataset"
    outputs:
      confusion_inputs:
        inputs:
          uncertainty_inputs: "Options_Sensor"
        losses:
          Multinomial_KL_Ensemble: 
            logging_name: "Confusion_Class"
        # evals: 
        #   Multinomial_Accuracy:
        #     logging_name: "uncertainty_accuracy"
        #   Multinomial_Entropy:
        #     logging_name: "uncertainty_entropy"
# "/scr-ssd/sens_search_logging/models/20200601_training_12_fit_wexpanded_action/"
  # Distance_Predictor:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     macro_action: "dataset"
  #     tool_type: "dataset"
  #     option_type: "dataset"
  #     permutation: "Options_Sensor"
  #     epoch: "dataset"
  #   outputs:
  #     distances:
  #       loss: "MSE"
  #       loss_name: "Distance_Prediction"
  #       weight: 1
  #       inputs:
  #         distances: "Options_Sensor"
  #       evals: ["Continuous_Error"]
  # Options_ConfMat:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     peg_type: "dataset"
  #     option_type: "dataset"
  #     options_est: "Options_Sensor"
  #     epoch: "dataset"


