relative_path: "../../supervised_learning/"

dataloading_params:
  dataset_path: "/scr2/muj_senssearch_dataset10HZ_slide_nonoise_expandedactions_20200513/" #"/scr2/muj_senssearch_dataset10HZ_slide_nonoise_expandedactions_20200512/" #"/scr2/muj_senssearch_dataset10HZ_slide_nonoise_20200428/"
  num_workers: 4
  batch_size: 128
  idx_dict_path: "/scr-ssd/sens_search_logging/runs/202005140913_training_14_fit_wexpanded_action/val_train_split.pkl" #"/scr-ssd/sens_search_logging/runs/202005131146_debugging_8_fit_wexpanded_action/val_train_split.pkl" #"/scr-ssd/sens_search_logging/runs/202005011634_debugging_2_conf_testing/val_train_split.pkl"

training_params:
  seed: 4321
  regularization_weight: 0.00001
  lrn_rate: 0.0001
  beta1: 0.9
  beta2: 0.99
  max_training_epochs: 2500
  val_ratio: 0.1
  dev_num: 20 # number of datapoints in the development set
  use_GPU: True
  run_mode: 1 # 0 - development, 1 - training, 2 - testing

logging_params:
  logging_folder: "/scr-ssd/sens_search_logging/" # Place your logging folder in a seperate location then your local code repository
  run_notes: "_fit_wexpanded_action"
  save_val_interval: 10 # epoch interval after which a validation run and save model is executed, i.e. a model is saved at 0, 10, 20, ..., 1000 epochs

custom_params:
  num_tools: 3
  num_options: 2
  force_size: [6, 50]
  action_size: 3
  pose_size: 3
  proprio_size: 12
  min_length: 20
  num_trajectories: 500
  
dataset_keys:
  # rgbd:
  # joint_pos:
  # joint_vel:
  force_hi_freq:
  action:
  macro_action:
  proprio:
  contact:
  peg_type:
  hole_type:
  fit_type:
  # insertion:

info_flow:
  Options_Sensor:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      proprio_diff: "dataset"
      force_hi_freq: "dataset"
      action: "dataset"
      peg_type: "dataset"
      contact_diff: "dataset"
      padding_mask: "dataset"
      epoch: "dataset"
    outputs:
      options_class:
        loss: "Multinomial_NLL"
        loss_name: "Options_Class"
        weight: 1
        inputs:
          fit_label: "dataset"
        evals:
          Multinomial_Accuracy:
          Multinomial_Entropy:
  Options_ConfNet:
    train: 1
    model_folder: ""
    epoch_num: 0
    inputs:
      macro_action: "dataset"
      peg_type: "dataset"
      option_type: "dataset"
      epoch: "dataset"
    outputs:
      conf_class:
        loss: "Multinomial_NLL"
        loss_name: "Confusion_Class"
        weight: 1
        inputs:
          option_est: "Options_Sensor"
        evals:
          Multinomial_Accuracy:
          Multinomial_Entropy:
  # Options_ConfMat:
  #   train: 1
  #   model_folder: ""
  #   epoch_num: 0
  #   inputs:
  #     peg_type: "dataset"
  #     option_type: "dataset"
  #     option_est: "Options_Sensor"
  #     epoch: "dataset"


